


name: Preview catalog
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
# do not allow running multiple of pipelines for this PR in parallel
concurrency: preview-${{ github.ref }}
jobs:
  preview_changed_files:
    runs-on: ubuntu-latest 
    permissions:
      contents: write
      pages: write
      pull-requests: write
    name: Deploy changed-files
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install eodash_catalog pyyaml
      - name: changed-files
        id: changed-files
        uses: tj-actions/changed-files@v45
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        # with:
        #   since_last_remote_commit: true 
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: python .github/update_catalog.py
      - name: Build
        env:
            SH_INSTANCE_ID: ${{ secrets.SH_INSTANCE_ID }}
            SH_CLIENT_ID: ${{ secrets.SH_CLIENT_ID }}
            SH_CLIENT_SECRET: ${{ secrets.SH_CLIENT_SECRET }}
        run: eodash_catalog
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
      - name: Set preview URL as status
        uses: actions/github-script@v7
        with:
          script: |
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              target_url: 'https://esa-eodashboards.github.io/eodashboard-catalog/pr-preview/pr-${{ github.event.pull_request.number }}/trilateral/catalog.json',
              description: 'Catalog preview ready!',
              context: 'Preview Deployment'
            })
